//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalComEntities : DbContext
    {
        public CalComEntities()
            : base("name=CalComEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IslemGecmisleri> IslemGecmisleri { get; set; }
        public DbSet<Mesajlar> Mesajlar { get; set; }
        public DbSet<Olcumler> Olcumler { get; set; }
        public DbSet<ParametreDegerleri> ParametreDegerleri { get; set; }
        public DbSet<ReferansCihazlar> ReferansCihazlar { get; set; }
        public DbSet<LabinReferansCihazlari> LabinReferansCihazlari { get; set; }
        public DbSet<OlcumdekiReferansCihaz> OlcumdekiReferansCihaz { get; set; }
        public DbSet<Laboratuvarlar> Laboratuvarlar { get; set; }
        public DbSet<OlcumNoktalari> OlcumNoktalari { get; set; }
        public DbSet<KayitBekleyenLab> KayitBekleyenLab { get; set; }
        public DbSet<Dosyalar> Dosyalar { get; set; }
        public DbSet<Testler> Testler { get; set; }
        public DbSet<OlcumSonuclari> OlcumSonuclari { get; set; }
        public DbSet<BasBekleyenTestler> BasBekleyenTestler { get; set; }
        public DbSet<KesinDegerler> KesinDegerler { get; set; }
        public DbSet<PerformanceScores> PerformanceScores { get; set; }
        public DbSet<StandartSapmalar> StandartSapmalar { get; set; }
        public DbSet<OlcumAletleri> OlcumAletleri { get; set; }
        public DbSet<Karsilastirmalar> Karsilastirmalar { get; set; }
    }
}
