//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosyalar
    {
        public int id { get; set; }
        public string İsim { get; set; }
        public string path { get; set; }
        public string Tur { get; set; }
        public string Açıklama { get; set; }
        public Nullable<int> İndirilmeSayisi { get; set; }
        public string Kod { get; set; }
    }
}
