//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemGecmisleri
    {
        public int Id { get; set; }
        public int LabId { get; set; }
        public string IslemAdi { get; set; }
        public string IslemTipi { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Laboratuvarlar Laboratuvarlar { get; set; }
    }
}
