//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KayitBekleyenLab
    {
        public int Id { get; set; }
        public string Isim { get; set; }
        public string Yonetici { get; set; }
        public string CalismaAlani { get; set; }
        public Nullable<long> VergiDairesiNo { get; set; }
        public Nullable<long> Telefon { get; set; }
        public Nullable<long> Faks { get; set; }
        public Nullable<long> Gsm { get; set; }
        public string Sehir { get; set; }
        public string Bolge { get; set; }
        public string Adres { get; set; }
        public byte[] Amblem { get; set; }
        public string Sifre { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    }
}
