//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int Id { get; set; }
        public int LabId { get; set; }
        public string Konu { get; set; }
        public Nullable<bool> Tur { get; set; }
        public Nullable<System.DateTime> MesajTarihi { get; set; }
        public string Mesaj { get; set; }
    
        public virtual Laboratuvarlar Laboratuvarlar { get; set; }
    }
}
