//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlcumAletleri
    {
        public OlcumAletleri()
        {
            this.Karsilastirmalar = new HashSet<Karsilastirmalar>();
        }
    
        public int Id { get; set; }
        public string Isim { get; set; }
        public string SeriNo { get; set; }
        public string Model { get; set; }
        public string İmalatci { get; set; }
        public string Cozunurluk { get; set; }
        public Nullable<double> Kapasite { get; set; }
        public string Birim { get; set; }
        public Nullable<double> Bölüntü { get; set; }
        public string Tip { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    
        public virtual ICollection<Karsilastirmalar> Karsilastirmalar { get; set; }
    }
}
