//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlcumNoktalari
    {
        public OlcumNoktalari()
        {
            this.OlcumSonuclari = new HashSet<OlcumSonuclari>();
            this.KesinDegerler = new HashSet<KesinDegerler>();
        }
    
        public int Id { get; set; }
        public int ParDerId { get; set; }
        public string OlcumNoktasi { get; set; }
    
        public virtual OlcumNoktalari OlcumNoktalari1 { get; set; }
        public virtual OlcumNoktalari OlcumNoktalari2 { get; set; }
        public virtual ParametreDegerleri ParametreDegerleri { get; set; }
        public virtual ICollection<OlcumSonuclari> OlcumSonuclari { get; set; }
        public virtual ICollection<KesinDegerler> KesinDegerler { get; set; }
    }
}
