//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlcumdekiReferansCihaz
    {
        public int Id { get; set; }
        public int LrcId { get; set; }
        public int OlcId { get; set; }
    
        public virtual LabinReferansCihazlari LabinReferansCihazlari { get; set; }
        public virtual Olcumler Olcumler { get; set; }
    }
}
