//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametreDegerleri
    {
        public ParametreDegerleri()
        {
            this.OlcumNoktalari = new HashSet<OlcumNoktalari>();
            this.StandartSapmalar = new HashSet<StandartSapmalar>();
        }
    
        public int ParDerId { get; set; }
        public int karid { get; set; }
        public string ParametreDegeri { get; set; }
        public string Birim { get; set; }
    
        public virtual ICollection<OlcumNoktalari> OlcumNoktalari { get; set; }
        public virtual ICollection<StandartSapmalar> StandartSapmalar { get; set; }
        public virtual Karsilastirmalar Karsilastirmalar { get; set; }
    }
}
