//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceScores
    {
        public int Id { get; set; }
        public int OlcumSonuclariId { get; set; }
        public string Yontem { get; set; }
        public Nullable<double> Deger { get; set; }
        public string Hesap { get; set; }
        public string Yorumlama { get; set; }
    
        public virtual OlcumSonuclari OlcumSonuclari { get; set; }
    }
}
