//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferansCihazlar
    {
        public ReferansCihazlar()
        {
            this.LabinReferansCihazlari = new HashSet<LabinReferansCihazlari>();
        }
    
        public int Id { get; set; }
        public string Konu { get; set; }
        public string Imalatci { get; set; }
        public string SeriNo { get; set; }
        public string Sinif { get; set; }
    
        public virtual ICollection<LabinReferansCihazlari> LabinReferansCihazlari { get; set; }
    }
}
