//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandartSapmalar
    {
        public int Id { get; set; }
        public int Testid { get; set; }
        public int ParDerId { get; set; }
        public Nullable<double> Deger { get; set; }
        public Nullable<double> Mean { get; set; }
        public string Yontem { get; set; }
    
        public virtual ParametreDegerleri ParametreDegerleri { get; set; }
        public virtual Testler Testler { get; set; }
    }
}
