//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calcom.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testler
    {
        public Testler()
        {
            this.Olcumler = new HashSet<Olcumler>();
            this.KesinDegerler = new HashSet<KesinDegerler>();
            this.StandartSapmalar = new HashSet<StandartSapmalar>();
        }
    
        public int Id { get; set; }
        public Nullable<int> karid { get; set; }
        public Nullable<System.DateTime> BaslangicZamani { get; set; }
        public Nullable<System.DateTime> BitisZamani { get; set; }
        public Nullable<System.DateTime> OlcumZamani { get; set; }
        public Nullable<System.DateTime> OlcumBitisZamani { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string Durum { get; set; }
        public string ProtokolNo { get; set; }
        public Nullable<short> OlcumSuresi { get; set; }
        public Nullable<byte> GerekenLabSayisi { get; set; }
        public string HesaplamaYontemi { get; set; }
    
        public virtual ICollection<Olcumler> Olcumler { get; set; }
        public virtual ICollection<KesinDegerler> KesinDegerler { get; set; }
        public virtual ICollection<StandartSapmalar> StandartSapmalar { get; set; }
        public virtual Karsilastirmalar Karsilastirmalar { get; set; }
    }
}
